### ISSUE TITLE
use e abuse de listas do python arthurio

### ISSUE THREAD

**Issue by talDoFlemis** [ApenasUmSonhador/projeto_calculadora_python#1]
Todo programador tem que ser preguiçoso, por isso use listas para evitar fazer muitos ifs

O códido de converter de decimal para a maioria dos outros sairia tipo isso
```python
def tubias(decimal, base):
    if decimal < 0 or base not in [2, 8, 16]:
        return None

    lista_safada = (
        "0123456789ABCDEF" if base == 16 else "01234567" if base == 8 else "01"
    )

    tubias = ""
    while decimal > 0:
        gepeto = decimal % base
        # aqui eh o poder de usar a lista, a gente pega o resto e usa como um
        # indice da lista
        # como nosso indice não passa do tamanho da lista a gente pode usar a
        # vontade
        # alem disso ele é exatamente o indice correto
        tubias = lista_safada[gepeto] + tubias
        decimal //= base

    return tubias
```

**Comment by ArthurViniNunes** [comment]
Entendido! Irado.
Modificando agora essa parte do código, muito maneiro!

**Comment by ArthurViniNunes** [comment]
Gratidão nobre amigo, creditos dados no código. 
Esse aprendizado estará guardado comigo e será aplicado em futuros códigos, além desse, claro.

**Comment by ArthurViniNunes** [comment]
Me inspirei na tua ideia para melhorar o código, veja que fica redundante eu colocar esses ifs, uma vez que o resto nunca será maior ou igual às bases.
